//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndieGames
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gamesStoreEntities : DbContext
    {
        public gamesStoreEntities()
            : base("name=gamesStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientsAndGame> ClientsAndGames { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Studio> Studios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
